openapi: 3.0.0
info:
  title: Chained SSRF Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './second.yaml'
